# Generated by Django 3.2.16 on 2023-06-19 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitinfo',
            name='detail',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='提交的姓名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commitinfo',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='提交的姓名'),
            preserve_default=False,
        ),
    ]
