# Generated by Django 3.2.16 on 2023-06-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commit', '0002_auto_20230619_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitinfo',
            name='detail',
            field=models.TextField(verbose_name='提交的姓名'),
        ),
    ]
