# Generated by Django 3.2.16 on 2023-06-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commit', '0003_alter_commitinfo_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitinfo',
            name='isIgnore',
            field=models.BooleanField(default=False, verbose_name='是否忽略'),
        ),
    ]
