# Generated by Django 3.2.16 on 2023-01-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskinfo',
            unique_together={('id', 'name')},
        ),
    ]
