# Generated by Django 3.2 on 2023-02-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_taskinfo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
