# Generated by Django 3.2 on 2023-02-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_taskinfo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
