# Generated by Django 3.2 on 2023-03-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_taskinfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='grade',
            field=models.CharField(default='高中低', max_length=255),
        ),
    ]
