# Generated by Django 3.2 on 2023-03-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_taskinfo_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='grade',
            field=models.CharField(default=['高', '中', '低'], max_length=255),
        ),
    ]
