# Generated by Django 3.2.18 on 2023-04-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_taskinfo_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
