# Generated by Django 3.2.18 on 2023-07-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='任务名')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('creator', models.CharField(max_length=225, verbose_name='创建人')),
                ('status', models.CharField(max_length=255, verbose_name='状态')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='报告链接')),
                ('performer', models.CharField(max_length=255, null=True, verbose_name='分配人')),
                ('start_time', models.DateTimeField(null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(null=True, verbose_name='结束时间')),
            ],
        ),
        migrations.DeleteModel(
            name='Autotest',
        ),
    ]
