# Generated by Django 3.2.18 on 2023-07-14 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_auto_20230714_1538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auto',
            new_name='AutoInfo',
        ),
    ]
