# Generated by Django 3.2.18 on 2023-07-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_rename_auto_autoinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoinfo',
            name='performer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='分配人'),
        ),
    ]
