# Generated by Django 3.2.18 on 2023-07-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_autoinfo_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoinfo',
            name='update_time',
        ),
    ]
