# Generated by Django 3.2.16 on 2023-01-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(null=True)),
                ('modules', models.CharField(max_length=255)),
                ('submodule', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('need', models.CharField(max_length=255, null=True)),
                ('precondition', models.TextField()),
                ('steps', models.TextField()),
                ('results', models.TextField()),
                ('type', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('priority', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=255)),
                ('performer', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'case',
            },
        ),
    ]
