# Generated by Django 3.2 on 2023-01-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_alter_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
