# Generated by Django 3.2 on 2023-02-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_alter_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='flag',
            field=models.BooleanField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='remark',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
