# Generated by Django 3.2 on 2023-04-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_auto_20230201_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
