# Generated by Django 3.2 on 2023-04-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_case_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name=models.CharField(blank=True, max_length=255, null=True)),
        ),
    ]
