# Generated by Django 3.2 on 2023-04-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0007_alter_case_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='status'),
        ),
    ]
