# Generated by Django 3.2.18 on 2023-04-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0008_alter_case_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='modules',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='priority',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(null=True),
        ),
    ]
