# Generated by Django 3.2.18 on 2023-04-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0009_auto_20230424_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='performer',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
