# Generated by Django 3.2.18 on 2023-04-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0012_auto_20230424_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='modules',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='performer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
