# Generated by Django 3.2.18 on 2023-07-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorun', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runinfo',
            name='task_id',
        ),
        migrations.AlterField(
            model_name='runinfo',
            name='report',
            field=models.URLField(blank=True, null=True, verbose_name='报告'),
        ),
    ]
