# Generated by Django 3.2.18 on 2023-07-21 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_remove_autoinfo_update_time'),
        ('autorun', '0002_auto_20230721_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='runinfo',
            name='task_id',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='auto.autoinfo'),
            preserve_default=False,
        ),
    ]
