# Generated by Django 3.2.18 on 2023-07-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorun', '0003_runinfo_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='runinfo',
            name='casenumber',
            field=models.IntegerField(default=0, max_length=20, verbose_name='用例数量'),
        ),
    ]
