# Generated by Django 3.2.18 on 2023-07-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorun', '0006_rename_casenumber_runinfo_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runinfo',
            name='report',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='报告'),
        ),
    ]
