# Generated by Django 3.2.18 on 2023-07-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorun', '0007_alter_runinfo_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='runinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
