# Generated by Django 3.2.18 on 2023-07-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempinfo',
            name='maintain',
            field=models.CharField(default=None, max_length=255, verbose_name='维护人'),
        ),
    ]
