# Generated by Django 3.2.18 on 2023-07-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0002_tempinfo_maintain'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempinfo',
            name='status',
            field=models.CharField(default='正常', max_length=20, verbose_name='状态'),
        ),
    ]
